# Generated by Django 6.0.7 on 2026-07-30 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmp', models.DateField(blank=True, null=True)),
                ('edd', models.DateField(blank=True, null=True)),
                ('gravida', models.PositiveIntegerField(default=1)),
                ('para', models.PositiveIntegerField(default=0)),
                ('medical_history', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mother', models.ForeignKey(limit_choices_to={'role': 'mother'}, on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
