# Generated by Django 6.0.7 on 2026-09-07 19:48

import mirage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancyrecord',
            name='medical_history',
            field=mirage.fields.EncryptedTextField(blank=True),
        ),
    ]
