# Generated by Django 6.0.7 on 2026-09-10 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_medicaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsrecord',
            name='blood_glucose_mg_dl',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='blood_pressure_diastolic',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='blood_pressure_systolic',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='fetal_movement_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vitalsrecord',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(300.0)]),
        ),
    ]
