# Generated by Django 6.0.7 on 2026-10-05 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_vitalsrecord_blood_glucose_mg_dl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsrecord',
            name='fetal_heart_rate_bpm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(220)]),
        ),
    ]
