# Generated by Django 6.0.7 on 2026-10-05 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0006_alter_vitalsrecord_blood_glucose_mg_dl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=20)),
                ('risk_score', models.FloatField(help_text='Probability of risk (0.0 to 1.0)')),
                ('contributing_factors', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(default='v1.0.0', help_text='Version of the ML model used for this assessment', max_length=50)),
                ('reviewed_by_doctor', models.BooleanField(default=False)),
                ('doctor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vitals_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='records.vitalsrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
