# Generated by Django 6.0.7 on 2026-09-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(unique=True)),
                ('baby_size', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mother_changes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('last_period_date', models.DateField(blank=True, null=True)),
                ('current_week', models.IntegerField(default=1)),
                ('mother', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField(default=list)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('ai_assessment', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
