# Generated by Django 6.0.7 on 2026-09-06 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctorprofile_motherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mother', 'Mother'), ('doctor', 'Doctor'), ('chw', 'Community Health Worker'), ('admin', 'Admin')], default='mother', max_length=10),
        ),
        migrations.CreateModel(
            name='CHWProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('assigned_region', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chw_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
