# Generated by Django 6.0.7 on 2026-10-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Requires doctor approval before full access'),
        ),
    ]
